[project]
name = "snowlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3",
    "duckdb>=1.1.3",
    "pandas>=2.2.3",
    "plotly>=5.24.1",
    "pyarrow",
    "s3fs",
    "streamlit>=1.40.0",
]
