name: Docker Push

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened

jobs:
  deploy-user:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: get version
        run: 'echo ''TAG=''${GITHUB_REF#refs/tags/} >> $GITHUB_ENV'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: '${{ github.repository_owner }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          pull: true
          tags: |
            ghcr.io/npelikan/snowlit:latest
            ghcr.io/npelikan/snowlit:${{ github.ref_name }}
            ghcr.io/npelikan/snowlit:${{ env.TAG }}
          platforms: 'linux/amd64,linux/arm64'
          cache-from: type=gha
          cache-to: 'type=gha,mode=max'
  
  update:
    name: update helm manifests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: deploy-user
    steps:
      - name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: chart/values.yaml
          propertyPath: image.tag
          value: '${{ github.ref_name }}'
          message: 'Update Image Version to ${{ github.ref_name }}'
