name: Docker Push

on:
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - reopened

jobs:
  deploy-user:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    outputs:
      commit_short_sha: ${{ steps.vars.outputs.COMMIT_SHORT_SHA}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: get version
        run: 'echo ''TAG=''${GITHUB_REF#refs/tags/} >> $GITHUB_ENV'
      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_OUTPUT
      - name: Confirm git commit SHA output
        run: echo ${{ env.COMMIT_SHORT_SHA }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: '${{ github.repository_owner }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          pull: true
          tags: |
            ghcr.io/npelikan/snowlit:${{ env.COMMIT_SHORT_SHA }}
          platforms: 'linux/amd64,linux/arm64'
          cache-from: type=gha
          cache-to: 'type=gha,mode=max'
  
  update:
    name: update helm manifests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: deploy-user
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Update Image Tag Values
        run: |
          chart_dir="chart"
          new_image_tag=${{ needs.deploy-user.outputs.commit_short_sha }}
  
          # Update the values.yaml file with the new image tag
          sed -i "s/^  tag: .*/  tag: $new_image_tag/" "$chart_dir/values.yaml"
      
      - name: Commit the changes made
        run: | 
          git config --global user.name 'Nick Pelikan'
          git config --global user.email 'npelikan@users.noreply.github.com'
          git commit -am "[automation] updating image tag in helm chart to ${{ needs.deploy-user.outputs.commit_short_sha }}"
          git push
